### ISSUE TITLE
Decision Channel goes offline when a source fails even if nothing CONSUMES the output of that source

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#27]
In our Nersc channel there is a NerscJobInfo source which produces a data block which nothing Consumes.
Nevertheless when this source failed, the whole channel was taken offline.  Framework needs to only fail if datablock is needed elsewhere.

**Comment by moibenko** [comment]
There are several ways of achieving your goal in existing configuration.

1. Re-write source so that it does not fail, but sends alarm or error message.

2. Remove source from configuration and restart channel.

On 1/14/19 10:11 AM, Steven Timm wrote:

In our Nersc channel there is a NerscJobInfo source which produces a data block which nothing Consumes.
Nevertheless when this source failed, the whole channel was taken offline. Framework needs to only fail if datablock is needed elsewhere.

**Comment by StevenCTimm** [comment]
Hopefully this issue will be addressed as part of the planned produces/consumes work in the framework development work package of the project.

**Comment by StevenCTimm** [comment]
The particular NerscJobInfo source hasn't been in the production config in more than 18 months.
Will discuss offline.  But this bug persists in 1.7

**Comment by StevenCTimm** [comment]
(Note that the source will come back once we have source namespaces, which was the core reason why the data block wasn't consumed by anthing.

**Comment by StevenCTimm** [comment]
The restructuring of DE 2.0 makes this bug moot.  Closing.
